language: python
sudo: true
addons:
    postgresql: "9.6"

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"

virtualenv:
  system_site_packages: false

services:
  - postgresql

before_install:
  - sudo apt-get update
  - sudo apt-get install graphviz

install:
  - pip install -U pip
  - pip install python_editor
  - pip install wheel
  - pip install psycopg2
  - pip install sqlalchemy
  - pip install flake8
  - pip install coverage
  - pip install nose
  - pip install colour
  - pip install passlib
  - pip install furl
  - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; pip install cryptography; fi
  - pip install phonenumbers
  - pip install pycountry
  - pip install coveralls
  - pip install texttable --no-binary
  - pip install PyYAML --no-binary
  - pip install python_editor --no-binary
  - python setup.py develop

env:
  global:
    - ANYBLOK_DATABASE_NAME=travis_ci_test
    - ANYBLOK_DATABASE_DRIVER=postgresql
    - ANYBLOK_DATABASE_USER=postgres

script:
  - flake8 anyblok
  - psql -c 'create database travis_ci_test;' -U postgres
  - nosetests anyblok/tests -v -s --with-coverage --cover-package=anyblok
  - psql -c 'drop database travis_ci_test;' -U postgres
  - anyblok_createdb --install-all-bloks
  - nosetests anyblok/bloks --with-anyblok-bloks -v -s --with-coverage --cover-package=anyblok
  
after_success:
  coveralls
