language: python
dist: xenial
sudo: true
addons:
    postgresql: "9.6"

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"
  - "pypy3.5"


matrix:
  allow_failures:
      - python: "3.8-dev"
      - python: "nightly"

virtualenv:
  system_site_packages: false

services:
  - postgresql

before_install:
  - sudo apt-get update
  - sudo apt-get install graphviz

install:
  - pip install -U pip
  # only wheel
  - pip install -U wheel
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy3.5' ]]; then pip install psycopg2cffi; else pip install psycopg2; fi
  - pip install -U sqlalchemy  # for unittesting anyblok with postgres
  - pip install -U flake8 coverage nose
  - pip install -U colour passlib furl phonenumbers pycountry  # special columns
  - pip install -U cryptography
  - pip install -U coveralls
  - python setup.py develop

env:
  global:
    - ANYBLOK_DATABASE_NAME=travis_ci_test
    - if [[ $TRAVIS_PYTHON_VERSION == 'pypy3.5' ]]; then ANYBLOK_DATABASE_DRIVER=postgresql+psycopg2cffi; else ANYBLOK_DATABASE_DRIVER=postgresql; fi
    - ANYBLOK_DATABASE_USER=postgres

script:
  - flake8 anyblok
  - psql -c 'create database travis_ci_test;' -U postgres
  - nosetests anyblok/tests -v -s --with-coverage --cover-package=anyblok
  - psql -c 'drop database travis_ci_test;' -U postgres
  - anyblok_createdb --install-all-bloks
  - nosetests anyblok/bloks --with-anyblok-bloks -v -s --with-coverage --cover-package=anyblok
  - anyblok_nose -- -v -s --with-coverage --cover-package=anyblok  # test runner
  
after_success:
  coveralls
